### ISSUE TITLE
Monitor does not close properly when run via ipython runfile (as in spyder)

### ISSUE THREAD

**Issue by Dominik-Vogel** [QCoDeS/Qcodes#1008]
Running:
```
from qcodes.monitor.monitor import Monitor
Monitor()
```
via runfile/F5 twice in spyder produces:
```
Traceback (most recent call last):
  File "C:\Users\a-dovoge\anaconda3\lib\asyncio\base_events.py", line 1044, in create_server
    sock.bind(sa)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a-dovoge\anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\a-dovoge\qcodes\qcodes\monitor\monitor.py", line 124, in run
    self.server = self.loop.run_until_complete(server_start)
  File "C:\Users\a-dovoge\anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\a-dovoge\anaconda3\lib\site-packages\websockets\server.py", line 365, in serve
    server = yield from loop.create_server(factory, host, port, **kwds)
  File "C:\Users\a-dovoge\anaconda3\lib\asyncio\base_events.py", line 1048, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 5678): only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by jenshnielsen** [comment]
Closed by #1009
