### ISSUE TITLE
Using `Lists` validator in `MultiType` Validator throws exception

### ISSUE THREAD

**Issue by StefanD986** [QCoDeS/Qcodes#1337]
If you encounter a bug use the following template.
If you have a feature request feel free to freestyle.
### Steps to reproduce
run this
```
python -c "from qcodes.utils.validators import Ints, Lists, MultiType; MultiType(Lists(Ints()), Ints())"
```

### Expected behaviour
`MultiType(Lists(Ints()), Ints())` should return a MultiType validator that accepts Lists of Ints or Ints.

### Actual behaviour
The above snippet throws a TypeError due to `class list` being not hashable.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/stefan/PycharmProjects/Qcodes/qcodes/utils/validators.py", line 467, in __init__
    self._valid_values = list(set(self._valid_values))
TypeError: unhashable type: 'list'
```

### System
OSX 10.14
Python 3.7
Qcodes git (master)

### My thoughts:
Further looking at the instruction where the error is thrown shows that the error occurs when the `self._valid_values` is converted to a set (in order to only keep unique values). Since the type of `Lists._valid_values` is a "list of lists" the implicit unpacking (by `+=`) of the list of lists that happens in Line 466  results in a list being appended to `MultiType._valid_values`

https://github.com/QCoDeS/Qcodes/blob/94f271b6c14599ed2bd7e303e77c993bb46c44fc/qcodes/utils/validators.py#L463-L467

From my point of view the best way to fix this is that `_valid_values` should always be a tuple instead of a list. However I have not looked at the details of the logic of what _valid_values is used for, so maybe it makes sense to have a list somewhere?

**Comment by WilliamHPNielsen** [comment]
@StefanD986, thanks for reporting this. And **congratulations** for opening issue number `1337`! 😄 

I like the idea of using tuples instead of lists for holding the `valid_values`, but I don't think there is any way around the `valid_values` for `Lists` being anything but a list. I'll post a PR shortly with an attempted solution.
