### ISSUE TITLE
error in add_results for large arrays

### ISSUE THREAD

**Issue by thibaudruelle** [QCoDeS/Qcodes#1440]
Within the measurement context manager, `add_result` fails for large `ArrayParameter`. For instance an array with shape (10, 1000001) works but an array with shape (16, 1000001) yields the error `sqlite3.DataError: string or blob too big` during the execution of `flush_data_to_database`.

### Steps to reproduce
1. Create Instrument with `ArrayParameter` whose get method returns an array of shape larger or equal to (16, 1000001)
2.  Create `meas = Measurement()` object, and register at least 3 such `ArrayParameter `(e.g. P1, P2, P3)
3.  Within the `meas.run() as datasaver` context, run `datasaver.add_result((P1, P1.get()),(P2, P2.get()),(P3, P3.get()))`

### Expected behaviour
The data should be flushed to the database without error.

### Actual behaviour
```
2019-01-11 12:18:29,291 ¦ qcodes.dataset.sqlite_base ¦ ERROR ¦ sqlite_base ¦ atomic ¦ 822 ¦ Rolling back due to unhandled exception
Traceback (most recent call last):
  File "c:\users\he5user\documents\software\experimentcontrol\qcodes\qcodes\dataset\sqlite_base.py", line 819, in atomic
    yield conn
  File "c:\users\he5user\documents\software\experimentcontrol\qcodes\qcodes\dataset\sqlite_base.py", line 1081, in insert_many_values
    c = transaction(conn, query, *flattened_values)
  File "c:\users\he5user\documents\software\experimentcontrol\qcodes\qcodes\dataset\sqlite_base.py", line 756, in transaction
    c.execute(sql, args)
sqlite3.DataError: string or blob too big
2019-01-11 12:18:29,300 ¦ qcodes.dataset.measurements ¦ WARNING ¦ measurements ¦ flush_data_to_database ¦ 390 ¦ Could not commit to database; Rolling back due to unhandled exception
2019-01-11 12:18:35,032 ¦ qcodes.dataset.sqlite_base ¦ ERROR ¦ sqlite_base ¦ atomic ¦ 822 ¦ Rolling back due to unhandled exception
Traceback (most recent call last):
  File "c:\users\he5user\documents\software\experimentcontrol\qcodes\qcodes\dataset\sqlite_base.py", line 819, in atomic
    yield conn
  File "c:\users\he5user\documents\software\experimentcontrol\qcodes\qcodes\dataset\sqlite_base.py", line 1081, in insert_many_values
    c = transaction(conn, query, *flattened_values)
  File "c:\users\he5user\documents\software\experimentcontrol\qcodes\qcodes\dataset\sqlite_base.py", line 756, in transaction
    c.execute(sql, args)
sqlite3.DataError: string or blob too big
2019-01-11 12:18:35,034 ¦ qcodes.dataset.measurements ¦ WARNING ¦ measurements ¦ flush_data_to_database ¦ 390 ¦ Could not commit to database; Rolling back due to unhandled exception
```

### Exact code to reproduce the error:
```
import qcodes as qc
from qcodes.instrument_drivers.TOPTICA.DLCpro import DLCpro
from qcodes.instrument_drivers.Keysight.KeysightAgilent_33XXX import WaveformGenerator_33XXX
from qcodes.instrument_drivers.TeledyneLeCroy.TD44MXsB import TD44MXsB

dlc = DLCpro('dlc', 'tcpip0::192.168.1.2::1998::socket')
awg = WaveformGenerator_33XXX('awg', 'TCPIP0::192.168.1.13::inst0::INSTR')
osc = TD44MXsB('osc', 'TCPIP0::192.168.1.7::INSTR')

station = qc.Station(dlc,awg,osc)
qc.new_experiment(name='test_cavity_dev', sample_name='fiber181')

# define parameters
wl_list = np.linspace(920, 925, 16)

# prepare for measurement
osc.trig_mode.set('single')
osc.memory_size(int(1e6))
osc.sequence.set('on')
osc.seq_segments.set(len(wl_list))
osc.C1.waveform_seq.prepare_waveform(seq_name=dlc.laser1.ctl.wavelength_act.name,
                                     seq_label=dlc.laser1.ctl.wavelength_act.label,
                                     seq_unit=dlc.laser1.ctl.wavelength_act.unit)
osc.C2.waveform_seq.prepare_waveform(seq_name=dlc.laser1.ctl.wavelength_act.name,
                                     seq_label=dlc.laser1.ctl.wavelength_act.label,
                                     seq_unit=dlc.laser1.ctl.wavelength_act.unit)
osc.C3.waveform_seq.prepare_waveform(seq_name=dlc.laser1.ctl.wavelength_act.name,
                                     seq_label=dlc.laser1.ctl.wavelength_act.label,
                                     seq_unit=dlc.laser1.ctl.wavelength_act.unit)

# define measurement
meas = Measurement()

meas.register_parameter(osc.C1.waveform_seq, paramtype='array')
meas.register_parameter(osc.C2.waveform_seq, paramtype='array')
meas.register_parameter(osc.C3.waveform_seq, paramtype='array')

# perform measurement
with meas.run() as datasaver:
    wl_act_list = []
    
    for wl_nm in wl_list:
        # set wavelength and wait for the laser to reach it
        dlc.laser1.ctl.wavelength_set.set(wl_nm)        
        while dlc.laser1.ctl.state() != 0:
            time.sleep(0.1)
            
        time.sleep(1)
        awg.force_trigger()
        time.sleep(1)
        
        # acquire oscilloscope traces
        wl_act_nm = dlc.laser1.ctl.wavelength_act.get()
        wl_act_list.append(wl_act_nm)

    osc.C1.waveform_seq.prepare_waveform(
        seq_name=dlc.laser1.ctl.wavelength_act.name,
        seq_label=dlc.laser1.ctl.wavelength_act.label,
        seq_unit=dlc.laser1.ctl.wavelength_act.unit,
        seq_setpoints=wl_act_list)
    osc.C2.waveform_seq.prepare_waveform(
        seq_name=dlc.laser1.ctl.wavelength_act.name,
        seq_label=dlc.laser1.ctl.wavelength_act.label,
        seq_unit=dlc.laser1.ctl.wavelength_act.unit,
        seq_setpoints=wl_act_list)
    osc.C3.waveform_seq.prepare_waveform(
        seq_name=dlc.laser1.ctl.wavelength_act.name,
        seq_label=dlc.laser1.ctl.wavelength_act.label,
        seq_unit=dlc.laser1.ctl.wavelength_act.unit,
        seq_setpoints=wl_act_list)
    
    datasaver.add_result((osc.C1.waveform_seq, osc.C1.waveform_seq.get()),
                         (osc.C2.waveform_seq, osc.C1.waveform_seq.get()),
                         (osc.C3.waveform_seq, osc.C1.waveform_seq.get()))
        
    run_id = datasaver.run_id

```
### System
Windows 10

PoggioLab/Qcodes/master

latest qcodes commit merged: b74ea5a

**Comment by thibaudruelle** [comment]
Side note: having 3 parameters is probably not necessary to reproduce the error. In my specific case it is necessary because the oscilloscope's buffer will not store more than 16 million samples.
