### ISSUE TITLE
Slack API deprecating early methods breaks qcodes.utils.slack.Slack class

### ISSUE THREAD

**Issue by haroldmeerwaldt** [QCoDeS/Qcodes#2806]
###
A couple of days ago, Slack deprecated some of its API:
[https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api](https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api)

Which breaks the get_im_ids method (and more probably).

The slacker package that is used by qcodes is no longer maintained and is archived:
[https://github.com/os/slacker/commit/3c7f43f75ee838be1121342c1aea1360388015e8](https://github.com/os/slacker/commit/3c7f43f75ee838be1121342c1aea1360388015e8)

Slack itself has a Python SDK:
[https://github.com/slackapi/python-slack-sdk](https://github.com/slackapi/python-slack-sdk)
which can replace the slacker package.

I will probably send in a PR next week.

### Steps to reproduce

import qcodes.utils.slack
bot_token = open(r'C:\Users\hbmeerwaldt\Desktop\qi_bot_token.txt').read()  
slacknames = ['haroldmeerwaldt']  
config = {'bot_name': 'QI','token': bot_token, 'names': slacknames}  
qcodes.utils.slack.Slack(config=config))
  

### Expected behaviour
A Slack instance is created successfully

### Actual behaviour
Traceback (most recent call last):
  File "C:\Users\hbmeerwaldt\QuTech\QuantumInspire\repositories\qubits-control\env\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-c8c171b87116>", line 1, in <module>
    qcodes.utils.slack.Slack(config=config)
  File "C:\Users\hbmeerwaldt\QuTech\QuantumInspire\repositories\qubits-control\env\lib\site-packages\qcodes\utils\slack.py", line 124, in __init__
    self.get_im_ids(self.users)
  File "C:\Users\hbmeerwaldt\QuTech\QuantumInspire\repositories\qubits-control\env\lib\site-packages\qcodes\utils\slack.py", line 235, in get_im_ids
    response = self.slack.im.list()
  File "C:\Users\hbmeerwaldt\QuTech\QuantumInspire\repositories\qubits-control\env\lib\site-packages\slacker\__init__.py", line 595, in list
    return self.get('im.list')
  File "C:\Users\hbmeerwaldt\QuTech\QuantumInspire\repositories\qubits-control\env\lib\site-packages\slacker\__init__.py", line 118, in get
    return self._request(
  File "C:\Users\hbmeerwaldt\QuTech\QuantumInspire\repositories\qubits-control\env\lib\site-packages\slacker\__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: method_deprecated

### System
Windows 10 Enterprise

master

7c5dca3956

**Comment by astafan8** [comment]
@haroldmeerwaldt hey, thanks for catching this! and thank you for the intention to submit a PR!
